packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  react-hook-form: ^7.56.1
  "@hookform/resolvers": "^5.0.1"
  typescript: ~5.8.3
  "@supabase/supabase-js": ^2.49.4

catalogs:
  react19:
    next: ^15.3.2
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ~19.0.10
    "@types/react-dom": ^19.0.4

  trpc11:
    "@trpc/server": 11.1.2
    "@trpc/client": 11.1.2
    "@trpc/react-query": 11.1.2
    "@trpc/next": 11.1.2
    "@tanstack/react-query": ^5.74.4
    "@tanstack/react-query-devtools": ^5.74.4
