packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  react-hook-form: ^7.56.1
  "@hookform/resolvers": "^5.0.1"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ~18.3.12
    "@types/react-dom": ^18.3.1
