name: CI

on:
  pull_request:
    branches: ["development"]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: migrating
        run: pnpm db:migrate

  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: seeding
        run: pnpm db:seed
