name: Database Seed

on:
  pull_request:
    branches-ignore:
      - "main"
  workflow_dispatch:

env:
  DATABASE_URL: ${{secrets.SHALLOW_DATABASE_URL}}
  SUPABASE_SERVICE_ROLE_KEY: ${{secrets.SHALLOW_SUPABASE_SERVICE_ROLE_KEY}}

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Install dependencies
        run: pnpm install

      - name: Seed
        run: pnpm db:seed
