name: Database Preview Migrate & Seed

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
      - name: migrating
        run: pnpm db:migrate

  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
      - name: seeding
        run: pnpm db:seed
