name: Database Seed

on:
  workflow_dispatch:

env:
  DATABASE_URL: ${{secrets.SHALLOW_DATABASE_URL}}
  NEXT_PUBLIC_SUPABASE_URL: ${{secrets.SHALLOW_SUPABASE_URL}}
  SUPABASE_SERVICE_ROLE_KEY: ${{secrets.SHALLOW_SUPABASE_SERVICE_ROLE_KEY}}

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - name: Install dependencies
        run: pnpm install
      - name: Seeding
        run: pnpm db:seed
